### ISSUE TITLE
Protocol docs link 404s

### ISSUE THREAD

**Issue by bibliotechy** [nytimes/tamper#4]
On http://nytimes.github.io/tamper/ the line :

`Full details of Tamper’s encoding scheme are in the protocol docs.` ends with a link, http://nytimes.github.io/tamper/Packs,  which 404s.

**Comment by bibliotechy** [comment]
Did yo mean to point here? https://github.com/NYTimes/tamper/wiki/Packs

**Comment by bkoski** [comment]
Good catch - just fixed.  Thanks!
