### ISSUE TITLE
Validator undefined in client...

### ISSUE THREAD

**Issue by designfrontier** [nytimes/tamper#7]
Not sure what I am missing but when I try and use the basic quick start I get 

Uncaught ReferenceError: Validator is not defined tamper.js:185

Not sure...

**Comment by dannguyen** [comment]
Same here, even when using the test data.

**Comment by designfrontier** [comment]
Just submitted a pull request that should fix this.

**Comment by bkoski** [comment]
Just merged pull req, this should be fixed now.  Sorry, was a bad copy/paste!
