### ISSUE TITLE
unpackData output is incomplete

### ISSUE THREAD

**Issue by volkanunsal** [nytimes/tamper#9]
Here is what I did. I ran the NyTimes scraper script in the examples folder. Took the packed data and pasted into the Chrome console. Then I put that data object through the Tamper.unpackData() function. The resulting output was an array with 341 or so objects. Each object had only a single property, guid. Every single attribute in the original was missing. Did I do something wrong? Can anyone replicate this?

**Comment by ArthurClemens** [comment]
I am seeing the same.

Delving a bit in `tamper.js` I see that the data needs to have the attibute `category` (other possibilities: `primary_status` and `badge`). This attribute is not included by the ruby script.

Change in `nyt_articles.rb` the lines with `pack.add_attribute` to include `filter_type: "category"`:

```
pack.add_attribute(
  attr_name: :byline,
  possibilities: possibilities[:byline],
  max_choices: 1,
  filter_type: "category"
)

pack.add_attribute(
  attr_name: :section_name,
  possibilities: possibilities[:section_name],
  max_choices: 1,
  filter_type: "category"
)
```

**Comment by volkanunsal** [comment]
:+1:

**Comment by ArthurClemens** [comment]
I see that `filter_type` is also not documented at https://github.com/NYTimes/tamper/wiki/JSONEnvelope

**Comment by bkoski** [comment]
Good catch!  That `filter_type` check was actually some cruft left over from one of our internal apps.  Updated tamper.js so that it validates `encoding` instead and rebuilt.
